### ISSUE TITLE
initial attempt

### ISSUE THREAD

**Issue by kylerlaird** [kylerlaird/tractobots#5]
I used "catkin_make" because I don't see "catkin" in the ros-kinetic-catkin package.  Is that correct?

I needed to install ros-kinetic-nodelet.
I'm getting a failure now because I don't have OpenCV installed.  Is that necessary?

**Comment by kylerlaird** [comment]
I tried running the partial build.  I needed to install ros-kinetic-xacro, ros-kinetic-visualization-msgs.

**Comment by kylerlaird** [comment]
Oh, boy...long day.  I've learned a few things...

I was planning to make my (Precision Planting) planter monitor a ROS node.  It's hardcoded to use /dev/ttyS1 for the GPS.  I thought I'd use socat and an /nmea_sentence subscriber to feed it.  That failed. It seemed to be failing to read before the subscriber got started.

So I switched to using gpsd and gpspipe.  That worked well for the planter monitor but the ROS gpsd_client didn't publish any fixes.

I decided to go back to my (ugly) Python dict solution but I added code to push NMEA sentences to the planter controller over UDP.  I use socat to route the messages to /dev/ttyS1.  That seems to work.

It's been raining, thankfully.  I'll try to get the rest of the pieces working and try a test tomorrow if it's dry.

**Comment by kylerlaird** [comment]
I also needed ros-kinetic-joint-state-publisher and ros-kinetic-robot-state-publisher.

**Comment by gavanderhoorn** [comment]
> I used "catkin_make" because I don't see "catkin" in the ros-kinetic-catkin package. Is that correct?

`catkin` is part of `catkin_tools`. On Ubuntu, install `python-catkin-tools`.

> I needed to install ros-kinetic-nodelet [..] ros-kinetic-xacro, ros-kinetic-visualization-msgs [..] ros-kinetic-joint-state-publisher and ros-kinetic-robot-state-publisher.

A quick check of the pkgs in the repository shows that they don't list their dependencies properly (in `package.xml`), otherwise a single `rosdep install --from-paths /path/to/your/catkin_ws/src --ignore-src` would have sufficed.

<del>Is there a particular reason btw that there is a full copy of the source of `marti_common` here? As [the readme](https://github.com/kylerlaird/tractobots/blob/068fc59ee46611406ed066a975b6c359c062948c/src/marti_common/README.md) shows, a `sudo apt-get install ros-$ROS_DISTRO-<package>` should be enough to install whatever is needed?</del> I guess you need to build from sources because you're on Kinetic. In any case, I'd recommend to use a `.rosinstall` file for setting up the workspace instead of copying entire packages.

**Comment by kylerlaird** [comment]
Thanks, gavanderhoorn!  python-catkin-tools helped.  I'll leave the packaging details to Alfonso.  I'd like to use (deb) packages as much as I can.

**Comment by gavanderhoorn** [comment]
> I'd like to use (deb) packages as much as I can.

should be possible. Just make sure the package manifests list all the necessary packages as `build_` and `exec_depend`s, then `rosdep install ..` should fix everything for you.

**Comment by solosito** [comment]
You are right @gavanderhoorn, actually that was my intention but I just uploaded a first version for letting @kylerlaird to start to work with it ASAP.

**Comment by kylerlaird** [comment]
`touch ./src/marti_common/CATKIN_IGNORE`

**Comment by solosito** [comment]
But we need some of the rest of the messages for mapviz. Just ignoring the conflicting one (```swri_opencv_util```) should be enough.
